### ISSUE TITLE
Make unlazy implicit

### ISSUE THREAD

**Issue by KOLANICH** [mirmik/evalcache#1]
https://github.com/ionelmc/python-lazy-object-proxy may be helpful for that.

**Comment by mirmik** [comment]
In fact, in the this library there is not as such an implicit unlazy. The library uses `__str__` overload to achieve this effect. That is, except for a case with `print(obj)`, this is nowhere else applicable.
But, I think, this is a good idea. It's comfortable.

Thank you.

**Comment by mirmik** [comment]
I hurried a little. Bad idea to overload `__repr__`. It's bad for debuging.  https://github.com/ionelmc/python-lazy-object-proxy doesn't did it too. So, only `__str__` overload for compatible with print.

https://github.com/Mirmik/evalcache/commit/da93ead708d9180ee23d36ec6ae92cab8104a731

**Comment by KOLANICH** [comment]
It doesn't only overload `__str__`, the main lib impl is in c++ code. It hooks into python for any access.  I have been using this lib in my projects for importing large optional dependencies lazily for quite a while. Read the docs and try to play with it yourself a little.


To do the trick you need to modify the c code.

**Comment by mirmik** [comment]
In which application does it work? Can you write a code or pseudocode of an operation in which implicit unwrapping occurs?

I don't see implicit unwrap on nonlazy-function invoke and etc... What situation you mean???

**Comment by mirmik** [comment]
In your case... https://github.com/KOLANICH/lazyImport.py

I think, evalcache doesn't need to support that behavior.
In fact... If you use attribute of lazy module object, how can i sure that you want take real object instead lazy object? Evalcache should return a lazy object for you. It is good behavior for lazy tree evaluation.

And it's realy bad idea to cache python module to disk. 
So... Then no. That behavior is not supported in this library.

**Comment by mirmik** [comment]
In evalcache you can prevent lazy module caching with evalcache.encache function:

```python
import evalcache
import importlib
lazy = evalcache.Lazy({})
lazy_import = lazy(importlib.import_module)
lazy_np = lazy_import("numpy")
lazy_array = lazy_np.array([3,3,3])
evalcache.encache(lazy_np, False)
lazy_array.unlazy() # array([3, 3, 3])
```

But, anyway that is lazy object.

**Comment by mirmik** [comment]
In version 1.2.0:

Add ```onplace``` and ```onuse``` options for implicit unlazing.
With ```onplace``` it worked right after lazyobject creation.
With ```onuse``` it worked in using moment.

Add Memoize decorator. It use implicit unlazing with ```dict``` as cache
