### ISSUE TITLE
артибуты экземпляров ленифицированных классов

### ISSUE THREAD

**Issue by sevkin** [mirmik/evalcache#4]
как мне добавить атрибут к уже созданой фигуре zencad что бы он сохранялся при её перемещении?

```python
import zencad

b = zencad.box(10,10,10)
b.e = 10
print(b.e) # ok

b1 = b.move(10,10,10)
print(b1.e) # AttributeError: object has no attribute 'e'
```

я хочу снабдить свежесозданную детальку некоторыми размерами, что бы её было проще подгонять по месту в сборке. добавить размеры прямо в детальку мне показалось наиболее логичным.

**Comment by mirmik** [comment]
Конкретно к Shape объектам такое применить врядли получится. Причина в том, что для поддержки "ленивости" библиотеки, операции над shape реализованы в функциональном стиле. Метод move не перемещает форму, но создаёт новую форму по образу прототипа, только перемещённую. И, соответственно, ничего лишнего в новосозданном объекте уже нет. 
(Кроме того, когда вы написали `b.e = 10`, вы создали поле не в самом объекте, а в его ленивой оболочке).

В zencad для есть модуль  zencad.assemble (https://mirmik.github.io/zencad/ru/assemble.html). Это модуль для работы со сборками. Он, к сожалению, плохо документирован, хотя в Examples есть примеры. Данный модуль предоставляет класс zencad.assemble.unit. Вы можете каждую деталь обернуть в unit, и такие объекты будут работать именно так, как вы ожидаете.

```python
#!/usr/bin/env python3
#coding: utf-8

from zencad import *
import zencad.assemble

u = zencad.assemble.unit([box(10)])
u.e = 10

u.move(10,10,10)
print(u.e)

disp(u)
show()
```

Но, надо понимать, что после оборачивания Shape в unit, никаких операций над Shape помимо перемещения сделать уже не получится. Поэтому сначала, подготавливается Shape, а потом создаётся unit для уже "готовой" детали.

**Comment by sevkin** [comment]
да, именно так я и сделал. для сборок. про сборку из одной детали - надеялся на лучшее, но пусть будет так. спасибо.
